
import 'package:project_manager/feature/customer/data/models/CustomerModel.dart';

import '../../../../core/network/auth/IApiclient.dart';

class RemoteDataSource {
  final IApiClient apiclient;
  RemoteDataSource(this.apiclient);

  Future<List<CustomerModel>> getAllCustomer() async {
    final data = await apiclient.get('/api/Customers') as List<dynamic>;
    return data
        .map((e) => CustomerModel.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  Future<CustomerModel> createCustomer(CustomerModel customer) async {
    final requestData = customer.toJson();
    // Remove id for create request since it will be generated by backend
    requestData.remove('id');
    final data = await apiclient.post('/api/Customers', requestData);
    return CustomerModel.fromJson(data as Map<String, dynamic>);
  }

  Future<CustomerModel> updateCustomer(CustomerModel customer) async {
    try {
      final data = await apiclient.put(
        '/api/Customers/${customer.id}',
        customer.toJson(),
      );
      // Nếu server trả về 204 (No Content), trả về customer hiện tại
      if (data == null) {
        return customer;
      }
      return CustomerModel.fromJson(data as Map<String, dynamic>);
    } catch (e) {
      throw Exception('Failed to update customer: $e');
    }
  }

  Future<void> deleteCustomer(int id) {
    return this.apiclient.delete('/api/Customers/$id');
  }
}
